# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param synth.incrementalSynthesisCache C:/Users/manci/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-14856-DESKTOP-JJK40NT/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.cache/wt} [current_project]
set_property parent.project_path {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/manci/AppData/Roaming/Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo {c:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Voltmeter_top.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Clock_voltmeter.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/ADC.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/VGA.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/FlipFlopD.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Counter_BCD_5_digits.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Counter_generic.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Comparator_X.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Comparator_simple.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Counter_33000.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Counter_uptoX.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/X_generator.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Counter_BCD.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Register_BCD_3.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/VGA_sync_control.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/VGA_data_gen.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/mux_8_in.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/mux_4_in.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/mux_bin_gen.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/font_rom.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/VGA_rgb_gen.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/VGA_H_sync.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/VGA_V_sync.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Visible_flag_generator.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/Counter_generic_bis.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/FlipFlopD_ena.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/VGA_H_counter.vhd}
  {C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/Voltimetro_Digital_Lucas_v1.srcs/sources_1/new/VGA_V_counter.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/Archivo de restricciones Arty-A7-35.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/Archivo de restricciones Arty-A7-35.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Voltmeter_top -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voltmeter_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voltmeter_top_utilization_synth.rpt -pb Voltmeter_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
