@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Dec 12 17:26:52 -0300 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim FlipFlopD_TB_1_behav -key {Behavioral:sim_1:Functional:FlipFlopD_TB_1} -tclbatch FlipFlopD_TB_1.tcl -view C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/FlipFlopD_TB_1_behav.wcfg -log simulate.log"
call xsim  FlipFlopD_TB_1_behav -key {Behavioral:sim_1:Functional:FlipFlopD_TB_1} -tclbatch FlipFlopD_TB_1.tcl -view C:/Users/manci/Desktop/Documentos Lucas/Academico/Materias Actuales y seminarios/Digital I/TP FINAL LUCAS/Voltimetro_Digital_Lucas_v1/FlipFlopD_TB_1_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
